version: "3.9"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    command: npm start

  postgres:
    image: postgres:12.7-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'C0V1D19'
      POSTGRES_DB: 'wallet_production'